kind: pipeline
name: default

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: clone
  image: drone/git
  commands:
  - git clone https://github.com/beancount/fava

- name: docker
  image: plugins/docker
  settings:
    dockerfile: fava/contrib/docker/Dockerfile
    repo: lbischof/fava-armhf
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
